name: possible
dependencies:
  - python=3.8   # or 3.7
  - pandas=1.3.2
  - seaborn=0.11.2
  - matplotlib=3.4.2
  - numpy=1.19.*
  - statsmodels=0.12.*
  - scikit-learn=0.24.*
  - xgboost
  - ipykernel
  - pydotplus